### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by Daniellavit** [oleksandrblazhko/ai-212-chervenkova#22]

**Comment by Daniellavit** [comment]
Завдання 1
Потреба - Поезія
Доступність = пусто
Зрозумілість = не дуже зрозуміло
Цінність = пусто
Актуальність = пусто
Обґрунтування мого вибору інформаційних умов:

Доступність - поезія є загальнодоступною інформацією на різних форматах, таких як відео, аудіокниги, інтерактивні програми
Зрозумілість - споживач може потребувати інформації про те, як розпочати написання творів, поліпшити свої навички поезії, прийняти участь у творчих конкурсах або фестивалях, а також про історію поезії, різні види поезії, відомих поетів і різноманітних стилів написання.
Цінність - інформація про поезію повинна бути корисною та актуальною. Вона повинна відповідати потребам та інтересам читачів.
Актуальність - регулярно оновлювати інформацію про поезію, щоб вона відповідала поточному моменту

**Comment by Daniellavit** [comment]
Завдання 2

Мета створення програмного продукту
Мета створення програмного продукту полягає в наданні інформаційної підтримки щодо вимірювання температури навколишнього середовища з урахуванням потреб в особистій безпеці праці під час написання поезії.

Обґрунтування того, що результати роботи прецедентів наближають користувача до досягнення мети

Прецедент "Авторизувати користувача"
Цей прецедент дозволяє користувачеві авторизуватися на сайті з продажу вимірювачів. Це є необхідним для того, щоб мати повний користувальницький функціонал, зокрема, можливість оплатити замовлення та отримати сповіщення про його успішність. Таким чином, виконання цього прецеденту наближає користувача до досягнення мети, оскільки дозволяє йому отримати доступ до необхідної інформації.

Прецедент "Оплатити замовлення"
Цей прецедент дозволяє користувачеві оплатити замовлення. Це необхідно для того, щоб отримати товар. Вимірювання температури навколишнього середовища є важливим фактором для особистої безпеки праці під час написання творів. Таким чином, виконання цього прецеденту наближає користувача до досягнення мети, оскільки дозволяє йому придбати вимірювач, який допоможе забезпечити належну температуру навколишнього середовища.

Прецедент "Сповіщати про успішність замовлення"
Цей прецедент дозволяє оператору магазину отримувати сповіщення про успішність замовлення. Це необхідно для того, щоб оператор магазину міг подзвонити або написати покупцю і підтвердити замовлення. Це також допомагає оператору магазину вчасно відправити товар покупцю. Таким чином, виконання цього прецеденту наближає оператора магазину до досягнення мети, оскільки дозволяє йому забезпечити належний сервіс покупцям.

Загальні висновки
Всі три прецеденти, описані в лабораторній роботі №2, сприяють досягненню мети програмного продукту. Вони дозволяють користувачам отримати доступ до необхідної інформації та придбати вимірювач, який допоможе забезпечити належну температуру навколишнього середовища. Оператори магазину також можуть використовувати ці прецеденти для надання належного сервісу покупцям.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
